import { type FormEvent, useEffect, useState } from 'react';
import { EmptyState, ErrorAlert, LoadingState, PageHeader } from '../components/Feedback';
import { Modal } from '../components/Modal';
import { api, ApiError } from '../lib/api';
import type { Assinatura, Plano, Usuario } from '../types';

export function FinanceiroPage() {
  const [plans, setPlans] = useState<Plano[] | null>(null);
  const [subscriptions, setSubscriptions] = useState<Assinatura[]>([]);
  const [users, setUsers] = useState<Usuario[]>([]);
  const [modal, setModal] = useState<'plan' | 'checkout' | null>(null);
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  const [planForm, setPlanForm] = useState({ nome: '', descricao: '', preco: '', duracaoMeses: '1' });
  const [checkout, setCheckout] = useState({ idUsuario: '', idPlano: '', metodoPagamento: 'PIX' });

  const load = async () => { try { const [planData, subscriptionData, people] = await Promise.all([api<Plano[]>('/planos'), api<Assinatura[]>('/assinaturas'), api<Usuario[]>('/usuarios')]); setPlans(planData); setSubscriptions(subscriptionData); setUsers(people); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Erro ao carregar financeiro'); } };
  useEffect(() => { void load(); }, []);

  async function createPlan(event: FormEvent) { event.preventDefault(); setSaving(true); try { await api('/planos', { method: 'POST', body: JSON.stringify({ ...planForm, preco: Number(planForm.preco), duracaoMeses: Number(planForm.duracaoMeses) }) }); setModal(null); setPlanForm({ nome: '', descricao: '', preco: '', duracaoMeses: '1' }); await load(); } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Erro ao criar plano'); } finally { setSaving(false); } }
  async function runCheckout(event: FormEvent) { event.preventDefault(); setSaving(true); try { await api('/checkout', { method: 'POST', body: JSON.stringify({ ...checkout, idUsuario: Number(checkout.idUsuario), idPlano: Number(checkout.idPlano) }) }); setModal(null); setCheckout({ idUsuario: '', idPlano: '', metodoPagamento: 'PIX' }); await load(); } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Erro no checkout'); } finally { setSaving(false); } }

  const revenue = subscriptions.flatMap((item) => item.pagamentos).reduce((sum, payment) => sum + Number(payment.valorPago), 0);
  return <>
    <PageHeader eyebrow="Negócio" title="Financeiro" description="Planos simples, assinaturas claras e uma visão saudável da operação." action={<div className="d-flex gap-2"><button className="btn btn-outline-dark" onClick={() => setModal('plan')}>Novo plano</button><button className="btn btn-primary" onClick={() => setModal('checkout')}><i className="bi bi-credit-card me-2" />Checkout</button></div>} />
    {error && <ErrorAlert message={error} />}
    <div className="finance-banner"><div><span className="eyebrow eyebrow--light">Receita registrada</span><strong>{revenue.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</strong><small>Somatório dos pagamentos na plataforma</small></div><i className="bi bi-graph-up-arrow" /></div>
    <section><div className="section-heading"><div><span className="eyebrow">Oferta</span><h2>Planos disponíveis</h2></div></div>{!plans ? <LoadingState /> : plans.length === 0 ? <EmptyState icon="bi-tags" title="Nenhum plano" description="Crie uma oferta para habilitar assinaturas." /> : <div className="plan-grid">{plans.map((plan, index) => <article className={`plan-card ${index === 1 ? 'featured' : ''}`} key={plan.idPlano}>{index === 1 && <span className="popular">Mais escolhido</span>}<span className="plan-index">0{index + 1}</span><h3>{plan.nome}</h3><p>{plan.descricao || 'Acesso aos conteúdos da plataforma.'}</p><div className="plan-price"><strong>{Number(plan.preco).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</strong><span>/ {plan.duracaoMeses} {plan.duracaoMeses === 1 ? 'mês' : 'meses'}</span></div><div className="plan-stat"><i className="bi bi-people" />{plan._count?.assinaturas ?? 0} assinaturas</div></article>)}</div>}</section>
    <section className="mt-5"><div className="section-heading"><div><span className="eyebrow">Movimento</span><h2>Assinaturas recentes</h2></div></div><div className="panel table-panel"><div className="table-responsive"><table className="table align-middle"><thead><tr><th>Cliente</th><th>Plano</th><th>Início</th><th>Validade</th><th>Pagamentos</th></tr></thead><tbody>{subscriptions.map((item) => <tr key={item.idAssinatura}><td><strong>{item.usuario.nomeCompleto}</strong><small className="d-block text-secondary">{item.usuario.email}</small></td><td>{item.plano.nome}</td><td>{new Date(item.dataInicio).toLocaleDateString('pt-BR')}</td><td>{new Date(item.dataFim).toLocaleDateString('pt-BR')}</td><td><span className="status-pill"><i />{item.pagamentos.length} registrado(s)</span></td></tr>)}</tbody></table>{subscriptions.length === 0 && <p className="text-center text-secondary py-4">Nenhuma assinatura registrada.</p>}</div></div></section>
    {modal === 'plan' && <Modal title="Novo plano" subtitle="Defina preço e duração da oferta." onClose={() => setModal(null)}><form className="modal-form" onSubmit={createPlan}><label className="form-label">Nome</label><input className="form-control" value={planForm.nome} onChange={(e) => setPlanForm({ ...planForm, nome: e.target.value })} required /><label className="form-label">Descrição</label><textarea className="form-control" rows={2} value={planForm.descricao} onChange={(e) => setPlanForm({ ...planForm, descricao: e.target.value })} /><div className="form-row"><div><label className="form-label">Preço</label><input className="form-control" type="number" step="0.01" min="0.01" value={planForm.preco} onChange={(e) => setPlanForm({ ...planForm, preco: e.target.value })} required /></div><div><label className="form-label">Duração (meses)</label><input className="form-control" type="number" min="1" value={planForm.duracaoMeses} onChange={(e) => setPlanForm({ ...planForm, duracaoMeses: e.target.value })} required /></div></div><button className="btn btn-primary w-100" disabled={saving}>{saving ? 'Salvando...' : 'Criar plano'}</button></form></Modal>}
    {modal === 'checkout' && <Modal title="Novo checkout" subtitle="Crie a assinatura e o pagamento em uma única operação." onClose={() => setModal(null)}><form className="modal-form" onSubmit={runCheckout}><label className="form-label">Pessoa</label><select className="form-select" value={checkout.idUsuario} onChange={(e) => setCheckout({ ...checkout, idUsuario: e.target.value })} required><option value="">Selecione</option>{users.map((user) => <option key={user.idUsuario} value={user.idUsuario}>{user.nomeCompleto}</option>)}</select><label className="form-label">Plano</label><select className="form-select" value={checkout.idPlano} onChange={(e) => setCheckout({ ...checkout, idPlano: e.target.value })} required><option value="">Selecione</option>{plans?.map((plan) => <option key={plan.idPlano} value={plan.idPlano}>{plan.nome} — {Number(plan.preco).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</option>)}</select><label className="form-label">Forma de pagamento</label><select className="form-select" value={checkout.metodoPagamento} onChange={(e) => setCheckout({ ...checkout, metodoPagamento: e.target.value })}><option value="PIX">PIX</option><option value="CARTAO_CREDITO">Cartão de crédito</option><option value="CARTAO_DEBITO">Cartão de débito</option><option value="BOLETO">Boleto</option></select><button className="btn btn-primary w-100" disabled={saving}>{saving ? 'Processando...' : 'Confirmar checkout'}</button></form></Modal>}
  </>;
}
